// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// kendall_weight_quick
double kendall_weight_quick(IntegerVector idx, const IntegerVector zC, const int nC, const int keyC, const Nullable<int> kC, const Nullable<NumericVector> uC);
RcppExport SEXP _kernrank_kendall_weight_quick(SEXP idxSEXP, SEXP zCSEXP, SEXP nCSEXP, SEXP keyCSEXP, SEXP kCSEXP, SEXP uCSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type zC(zCSEXP);
    Rcpp::traits::input_parameter< const int >::type nC(nCSEXP);
    Rcpp::traits::input_parameter< const int >::type keyC(keyCSEXP);
    Rcpp::traits::input_parameter< const Nullable<int> >::type kC(kCSEXP);
    Rcpp::traits::input_parameter< const Nullable<NumericVector> >::type uC(uCSEXP);
    rcpp_result_gen = Rcpp::wrap(kendall_weight_quick(idx, zC, nC, keyC, kC, uC));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_kernrank_kendall_weight_quick", (DL_FUNC) &_kernrank_kendall_weight_quick, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_kernrank(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
