# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kendall_weight_quickR <- function(idxR, zR, nR, keyR, kR, uR) {
    .Call('_kernrank_kendall_weight_quickR', PACKAGE = 'kernrank', idxR, zR, nR, keyR, kR, uR)
}

